services:
  diplomancy_db:
    container_name: diplomancy_db
    image: docker.io/library/postgres:18.4
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: diplomancy_db
      POSTGRES_USER: diplomancy
      POSTGRES_PASSWORD: password1234

    volumes:
      - ./data:/var/lib/postgresql/18/docker:Z

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "diplomancy", "-d", "diplomancy_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
