services:
  diplomancy_db:
    container_name: ${CONATINER_NAME}
    image: docker.io/library/postgres:18.4
    restart: unless-stopped

    ports:
      - "${DB_PORT}:5432"

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: diplomancy
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - ./data:/var/lib/postgresql/18/docker:Z

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U diplomancy -d diplomancy_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
